import React from 'react';
import {StyleSheet, Dimensions} from 'react-native';
import deviceInfoModule from 'react-native-device-info';
import {Color, font} from '../../constants';
import COLOR from '../../constants/colors';
import {dpFont, dpWidth} from '../../utils/SizeInDp';

const windowWidth = Dimensions.get('window').width;
// eslint-disable-next-line no-unused-vars
const windowHeight = Dimensions.get('window').height;

export default style = StyleSheet.create({
  mainView: {
    width: '100%',
    height: '100%',
    flex: 1,
    backgroundColor: Color.bgColor,
  },
  mainItemView: {
    flexDirection: 'row',
    marginBottom: windowWidth * 0.09,
    paddingTop: windowWidth * 0.04,
  },
  mainItemView2: {
    flexDirection: 'row',
    marginBottom: windowWidth * 0.03,
    paddingTop: windowWidth * 0.04,
  },
  mainBottomView: {
    position: 'absolute',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%',
  },
  mainJamiatView: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  bottomView: {flex: 1},
  lineargradient2: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowWidth * 0.02,
    paddingVertical: windowWidth * 0.02,
    paddingHorizontal: windowWidth * 0.04,
    marginLeft: 10,
    marginHorizontal: 10,
    borderWidth: 1,
    width: '100%',
  },
  buttontext2: {
    color: Color.black,
    fontSize: font.fontSizes15,
    fontWeight: '700',
  },
  niyat_container: {flex: 1, height: '100%', backgroundColor: Color.bgColor},
  backgroundImg: {position: 'absolute'},
  back_icon: {padding: '3%'},
  niyat_search_view: {paddingTop: '2%'},
  niyat_list_view: {
    // marginTop: '3%',
    paddingTop: '5%',
    height: deviceInfoModule.isTablet() ? '98%' : '95%',
    paddingBottom: '30%',
    marginBottom: '5%',
  },
  uparrow_view: {
    position: 'absolute',
    bottom: '2%',
    alignSelf: 'flex-end',
  },
  list_item_view: {
    paddingHorizontal: '3%',
    marginVertical: '2%',
    // marginBottom: '10%',
  },
  question_txt: {
    color: Color.bottomTab,
    fontSize: font.fontSizes13,
    fontWeight: '400',
  },
  question_heading: {
    color: Color.bottomTab,
    fontSize: font.fontSizes12,
    fontWeight: '700',
  },
  title_headingView: {flexDirection: 'column', flex: 1},
  title_heading: {
    color: Color.bottomTab,
    // flex: 1,
    fontSize: font.fontSizes12,
    fontWeight: 'bold',
  },
  item_txt: {
    color: Color.bottomTab,
    // flex: 1,
    fontSize: font.fontSizes11,
  },
  btn_view: {
    borderRadius: 5,
    justifyContent: 'center',
    padding: 8,
    marginLeft: '2%',
    // height: 25
  },
  bgView: {position: 'absolute'},
  upArrow: {bottom: '39%'},
  startView: {backgroundColor: Color.bgColor},
  lineargradient: {borderRadius: 5, paddingHorizontal: 2, paddingVertical: 2},
  card: {
    backgroundColor: Color.bgColor,
    borderRadius: 5,
    paddingVertical: dpWidth(15),
    paddingHorizontal: dpWidth(13),
  },
  iconStyle: {padding: '5%'},
  cardContent: {justifyContent: 'center'},
  qustionViw: {width: '100%'},
  title_heading_outerView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  midView: {width: '100%', flex: 1},
  approve_niyt_info_view: {
    margin: '1%',
    flex: 1,
    flexDirection: 'row',
    // justifyContent: 'space-evenly',
    alignItems: 'center',
    height: '80%',
    right: '3%',
  },
  approve_niyt_touchablity: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: '3%',
  },
  closeIconView: {width: '10%'},
  modalInerViw: {flexDirection: 'row', width: '100%'},
  iconOuterView: {width: '90%'},

  ////send msg style///////////
  safeView: {backgroundColor: Color.bgColor, height: '100%'},
  bGView: {position: 'absolute'},
  iconStyyle: {padding: '3%', marginTop: '5%'},
  umoorHeadView: {
    width: '90%',
    backgroundColor: '#fff',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    marginVertical: '3%',
    shadowRadius: 3,
    borderWidth: 2,
    padding: 3,
    borderColor: '#F2EBB9',
    borderRadius: 6,
  },
  ummorCheckBoxView: {
    width: '100%',
    height: 50,
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
  },
  umoorHeadMainView: {
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: '4%',
  },
  messageView: {
    width: '100%',
    marginTop: '4%',
  },
  messageTxt: {
    color: COLOR.drawarActiveTintColor,
    fontWeight: '300',
    textAlign: 'justify',
    marginHorizontal: dpWidth(10),
  },
  chckBoxView: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    alignContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  inputView: {
    width: '60%',
    height: '80%',
    margin: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F2EBB9',
    backgroundColor: '#FFFFFF',
  },
  inputStyle: {
    height: 30,
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  listchckBoxView: {flexDirection: 'row', flex: 1},
  listView: {marginRight: '2%'},
  show_more_touch: {
    width: '100%',
    borderTopWidth: 1,
    marginTop: '3%',
    borderColor: '#F2EBB9',
  },
  show_more_view: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: '4%',
  },
  show_more_txt: {color: COLOR.headtextColor},
  check_view: {
    width: '100%',
    height: 50,
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
  },
  item_name_txt: {width: '70%'},
  chech_outside_view: {
    width: '90%',
    backgroundColor: '#fff',
    shadowColor: '#171717',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    marginVertical: '1%',
    shadowRadius: 3,
    borderWidth: 2,
    padding: 3,
    borderColor: '#F2EBB9',
    borderRadius: 6,
  },
  send_cancel_txt: {
    color: Color.black,
    fontSize: font.fontSizes16,
    fontWeight: '500',
    paddingVertical: 12,
    borderRadius: 20,
    textAlign: 'center',
  },
  input_msg_style: {
    height: 100,
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingLeft: '3%',
    borderColor: '#F2EBB9',
    borderWidth: 1,
    width: '95%',
  },
  input_sub_style: {
    alignContent: 'center',
    alignSelf: 'center',
    height: '100%',
    alignItems: 'stretch',
    borderRadius: 10,
    paddingLeft: '3%',
    backgroundColor: '#fff',
    justifyContent: 'center',
    borderWidth: 1,
    paddingVertical: '4%',
    borderColor: '#F2EBB9',
  },
  sub_input_view: {width: '95%', marginTop: '3%'},
  liner_gredient_view: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  liner_gredient_style: {borderRadius: 7, width: '45%'},
  background_viw: {position: 'absolute'},
});
