/* eslint-disable no-unused-vars */
/* eslint-disable no-undef */
import {StyleSheet, Dimensions, PixelRatio} from 'react-native';
import {Color, font} from '../../constants';
import {dpHeight} from '../../utils/SizeInDp';
import {appScreen} from '../../utils/responsive/SizeUtil';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const {height, width} = Dimensions.get('window');

export default styles = StyleSheet.create({
  row: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginHorizontal: 15,
    marginBottom: 15,
    backgroundColor: Color.bgColor,
    elevation: 6,
    borderWidth: 2,
    borderColor: '#e5b43b',
    borderRadius: 10,
  },
  text: {
    fontSize: font.fontSizes12,
    color: Color.titleColor,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  qtext: {
    fontSize: font.fontSizes12,
    color: Color.titleColor,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },

  ctext: {
    fontSize: 14,
    color: Color.titleColor,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 10,
    textAlign: 'center',
  },
  /* Niyat Infromation Model Style  */

  centeredView: {
    // flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    height: windowHeight,
  },
  trophytext1: {
    position: 'absolute',
    bottom: '30%',
  },
  trophytext2: {
    fontSize: font.fontSizes18,
    fontWeight: '500',
  },

  modalView: {
    backgroundColor: Color.bgColor,
    marginHorizontal: '10%',
    alignItems: 'center',
    borderRadius: 10,
    paddingBottom: '4%',
    justifyContent: 'center',
    // paddingBottom: '10%',
    paddingHorizontal: 10,
    shadowColor: Color.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalView2: {
    // backgroundColor: Color.bgColor,
    marginHorizontal: '10%',
    alignItems: 'center',
    borderRadius: 10,
    justifyContent: 'center',
    // paddingBottom: '10%',
    height: windowHeight / 3.9,
    // paddingHorizontal: 10,
  },
  itemBorder: {
    height: windowWidth * 0.25,
    width: windowWidth * 0.27,
    position: 'absolute',
  },
  bottomBord: {
    height: windowWidth * 0.25,
    width: windowWidth * 0.27,
    position: 'absolute',
    // justifyContent: 'flex-end',
  },
  buttonClose: {
    width: '100%',
    alignItems: 'flex-end',
    // paddingTop: 5,
  },
  textStyle: {
    color: Color.titleColor,
    fontSize: font.fontSizes16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  responseText: {
    color: Color.titleColor,
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  linear: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    color: Color.black,
    fontWeight: '500',
    paddingHorizontal: windowWidth * 0.03,
    paddingVertical: windowWidth * 0.015,
  },
  textBox: {
    borderColor: 'red',
    borderRadius: 5,
    borderWidth: 0.5,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignSelf: 'baseline',
    padding: 5,
    marginBottom: 10,
  },
  lineargradient2: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowWidth * 0.02,
    paddingVertical: windowWidth * 0.01,
    paddingHorizontal: windowWidth * 0.04,
    marginLeft: 10,
    marginHorizontal: 10,
  },
  buttontext1: {
    color: Color.black,
    fontSize: font.fontSizes15,
    fontWeight: '400',
  },
  buttontext2: {
    color: Color.black,
    fontSize: font.fontSizes15,
    fontWeight: '400',
  },
  modelInputView: {
    flexDirection: 'column',
    // backgroundColor: 'red',
    width: '100%',
    marginBottom: PixelRatio.getPixelSizeForLayoutSize(3),
    justifyContent: 'space-between',
    // height: '40%',

    // alignItems: 'center',
  },
  modelInput: {
    width: '100%',
    backgroundColor: Color.white,
    // borderWidth: 0.5,
    // borderColor: Color.grey,
    borderRadius: 6,
    height: dpHeight(27),
    // height: PixelRatio.getPixelSizeForLayoutSize(9),
    padding: 0,
    // paddingLeft: '3%',
    paddingHorizontal: '5%',
    justifyContent: 'center',
  },
  modelInputText: {
    fontWeight: '400',
    color: Color.black,
    fontSize: font.fontSizes13,
    width: '100%',
    textAlign: 'justify',
    paddingBottom: dpHeight(4),
  },
  button_View: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    position: 'absolute',
    bottom: dpHeight(20),
  },
  gift_txt: {
    fontSize: font.fontSizes20,
    fontWeight: 'bold',
    color: Color.bottomTab,
    paddingTop: 18,
    // textAlign: 'center',
    // justifyContent: 'flex-start',
  },
  gift_view: {
    flexDirection: 'row',
    width: '100%',
    // justifyContent: 'space-between',
    paddingHorizontal: 10,
    position: 'absolute',
    top: 0,
    justifyContent: 'center',
  },
  close_icon: {
    marginTop: 25,
    left: 7,
  },
  trophyView: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    // paddingHorizontal: 10,
    marginTop: 9,
    position: 'absolute',
    top: dpHeight(40),
  },
  trophyTxt: {
    color: Color.black,
    justifyContent: 'center',
    fontWeight: '400',
    fontSize: font.fontSizes16,
  },
  trophyCount: {
    color: Color.black,
    fontWeight: 'bold',
    fontSize: font.fontSizes16,
  },
  scrollView: {flex: 1, height: height},
  touchable_view: {flex: 1},
  img_background: {borderRadius: 10},
  img_bacgrnd_view: {
    backgroundColor: Color.white,
    width: '80%',
    alignSelf: 'center',
    padding: '2%',
    borderRadius: 15,
  },
  modl: {margin: 0},
  pendingView: {
    marginLeft: 10,
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: 'red',
  },
  doneView: {
    marginLeft: 10,
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: '#55A566',
  },
  pending_txt: {
    // backgroundColor: 'red',
    paddingHorizontal: 15,
    paddingVertical: 0.5,
    color: Color.titleColor,
    fontSize: font.fontSizes,
  },
  done_txt: {
    paddingHorizontal: 15,
    paddingVertical: 0.5,
    color: '#573802',
    fontSize: font.fontSizes,
  },
  niyatInfo_heading_view: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginVertical: 15,
  },
  niyatInfo_heading_txt: {
    fontSize: font.fontSizes16,
    fontWeight: 'bold',
    color: Color.titleColor,
    marginLeft: 10,
  },
  mumin_name_txt: {
    color: Color.titleColor,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  yes_txt: {
    fontSize: font.fontSizes,
    color: '#573802',
    marginLeft: 5,
    marginRight: 10,
  },
  no_txt: {
    fontSize: font.fontSizes,
    color: '#573802',
    marginLeft: 5,
  },
  fill_date_txt: {
    fontSize: font.fontSizes,
    color: Color.titleColor,
    marginLeft: 10,
  },
  fill_date_view: {flexDirection: 'row', justifyContent: 'space-between'},
  trophy_view: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: '2%',
  },
  trophy_txt: {
    color: Color.black,
    textAlign: 'center',
    bottom: '26%',
    fontSize: font.fontSizes20,
    fontWeight: '500',
    marginEnd: '2%',
  },
  request_submit_txt: {
    fontSize: font.fontSizes12,
    fontWeight: 'bold',
    color: Color.titleColor,
  },
  approverone_txt: {
    fontSize: font.fontSizes,
    color: Color.titleColor,
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    marginTop: 10,
  },
  send_msg_txt: {
    textAlign: 'center',
    color: Color.titleColor,
    fontSize: font.fontSizes12,
    fontWeight: 'bold',
  },
});
