// Quiz Action Types
export const QUIZ_LOADING = 'QUIZ_LOADING';
export const QUIZ_LOADED = 'QUIZ_LOADED';
export const QUIZ_ERROR = 'QUIZ_ERROR';
export const QUIZ_SUBMIT_LOADING = 'QUIZ_SUBMIT_LOADING';
export const QUIZ_SUBMITTED = 'QUIZ_SUBMITTED';
export const QUIZ_SUBMIT_ERROR = 'QUIZ_SUBMIT_ERROR';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SET_ANSWER = 'SET_ANSWER';
export const RESET_QUIZ = 'RESET_QUIZ';

// Quiz Access Types
export const QUIZ_ACCESS_LOADING = 'QUIZ_ACCESS_LOADING';
export const QUIZ_ACCESS_SUCCESS = 'QUIZ_ACCESS_SUCCESS';
export const QUIZ_ACCESS_ERROR = 'QUIZ_ACCESS_ERROR';

// User Quizzes List Types
export const USER_QUIZZES_LOADING = 'USER_QUIZZES_LOADING';
export const USER_QUIZZES_SUCCESS = 'USER_QUIZZES_SUCCESS';
export const USER_QUIZZES_ERROR = 'USER_QUIZZES_ERROR';

// Submit Answer Types
export const SUBMIT_ANSWER_LOADING = 'SUBMIT_ANSWER_LOADING';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';
